### ISSUE TITLE
Consider switching from React to Vue.js

### ISSUE THREAD

**Issue by 24** [dalyIsaac/onenote-markdown#6]
hi man:

if  this a new project . i suggest  you can try VUE  .
you will be found some thing.

**Comment by dalyIsaac** [comment]
Do you have a specific advantage which would make it worthwhile? I initially chose React because of the ability to easily use the Office UI Fabric components.

**Comment by 24** [comment]
ok .yes,, office-ui-fabric-react best  :+1:
