### ISSUE TITLE
click page title in pagesNav,not show page content

### ISSUE THREAD

**Issue by 24** [dalyIsaac/onenote-markdown#63]
hi , thanks you share this project . very cool project .

chrome version: 
 Version 70.0.3538.77 (Official Build) (64-bit)  linux 

QA:
click page title in pagesNav, can't  show page content , but http response return content . maybe view not refresh ?

desc:
but ,i see ,http response return  page content .(very slow , 20 s )
```
https://graph.microsoft.com/v1.0/users/xxxxxxx/onenote/pages/0-9e02a1aa4999bd439c5a92a43f06db13!1-BDB22EDA5D09048A!121949/content
```

I do not know how to relove this problem .....

**Comment by dalyIsaac** [comment]
I haven't actually implemented code to interact with the content yet - I'll start looking at that soon.

Isaac

________________________________

**Comment by 24** [comment]
hahahaha  ok ..  
 looking forward to your update . 👍
